"""add resource_image_url

Revision ID: 3e27d832ef03
Revises: 49d21076a479
Create Date: 2025-03-24 14:12:21.325054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e27d832ef03'
down_revision = '49d21076a479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('resource_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'resource_image_url')
    # ### end Alembic commands ###
