"""add fields to image

Revision ID: 934c7689975f
Revises: 087ff83dfbae
Create Date: 2025-02-04 18:50:51.592125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934c7689975f'
down_revision = '087ff83dfbae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
