"""add fields

Revision ID: 49d21076a479
Revises: 934c7689975f
Create Date: 2025-02-04 15:55:22.182522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d21076a479'
down_revision = '087ff83dfbae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('prompt', sa.String(), nullable=False))
    op.add_column('images', sa.Column('image_size', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_size')
    op.drop_column('images', 'prompt')
    # ### end Alembic commands ###

