"""add resource_image_url

Revision ID: a0e7ecb22366
Revises: 49d21076a479
Create Date: 2025-03-24 14:04:36.870282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e7ecb22366'
down_revision = '49d21076a479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_size')
    op.drop_column('images', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('image_size', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
